WindowManager: 
    loginWindow: 
    signupWindow:
    homepage:

# GUI for the login window 
<loginWindow>: 
    email : email 
    pwd : pwd
    Image:
        source:r"Design\LoginDesign.jpg"
        allow_stretch: True
        keep_ratio: False
    TextInput: 
        id : email 
        multiline :False
        size_hint : (.2, .034)
        pos_hint : {'center_x':.490, 'center_y':.505}
    TextInput: 
        id : pwd 
        multiline :False
        size_hint : (.2, .034)
        pos_hint : {'center_x':.490, 'center_y':.410}
        password: True
    Button: 
        text : "Create an account"
        size_hint : 0.2, 0.1
        pos_hint : {'center_x':.480, 'center_y':.130}
        on_release:  
            app.root.current = 'signup'
            root.manager.transition.direction = "down"
    Button:
        size_hint : 0.15, 0.1
        pos_hint :{'center_x':.480, 'center_y':.260}
        background_normal:"Design\loginbutton.jpg"
        on_release:
            root.login() 
            root.manager.transition.direction = "up"
<signupWindow>:
    firstname : fname
    lastname : lname
    mail : email
    phone_no : phno
    pswd : password
    c_pswd : current_password
    addr : address
    d_o_b : dob
    Image:
        source:r"Design\BackDesign.jpg"
        allow_stretch: True
        keep_ratio: False 
    TextInput:
        id : fname
        size_hint :(.2, .034)
        pos_hint :{'center_x':.322, 'center_y':.784}
        multiline: False
    TextInput:
        id : lname
        size_hint :(.2, .034)
        pos_hint :{'center_x':.712, 'center_y':.784}
        text :""
        multiline: False
    TextInput:
        id : email
        size_hint :(.2, .034)
        pos_hint :{'center_x':.322, 'center_y':.645}
        text :""
        multiline: False
    TextInput:
        id : phno
        size_hint :(.2, .034)
        pos_hint :{'center_x':.712, 'center_y':.645}
        text :""
        multiline: False
    TextInput:
        id : password
        size_hint :(.2, .034)
        pos_hint :{'center_x':.322, 'center_y':.504}
        text :""
        password: True
        multiline: False
    TextInput:
        id : current_password
        size_hint :(.2, .034)
        pos_hint :{'center_x':.712, 'center_y':.504}
        text :""
        multiline: False
        password: True
    TextInput:
        id : address
        size_hint :(.2, .135)
        pos_hint :{'center_x':.712, 'center_y':.313}
        text :""
    TextInput:
        id : dob
        size_hint :(.2, .034)
        pos_hint :{'center_x':.322, 'center_y':.260}
        text :""
        hint_text:'dd-mm-yyyy'
    CheckBox:
        group:"Gender"
        color:.294, .761, .623
        on_active: root.checkbox_click(self, self.active,"Male")
        size_hint :(.05, .034)
        pos_hint :{'center_x':.260, 'center_y':.356}
    CheckBox:
        group:"Gender"
        color:.294, .761, .623
        on_active: root.checkbox_click(self, self.active,"Female")
        size_hint :(.05, .034)
        pos_hint :{'center_x':.330, 'center_y':.356}
    CheckBox:
        group:"Gender"
        color:.294, .761, .623
        on_active: root.checkbox_click(self, self.active,"Prefer not to say")
        size_hint :(.05, .034)
        pos_hint :{'center_x':.440, 'center_y':.356}
    Button:
        size_hint :(.1, .1)
        background_color :[1,1,1,1]
        pos_hint :{'center_x':.5, 'center_y':.190}
        background_normal:"Design\Submit.png"
        on_release :
            root.val()
    Button:
        size_hint :(.2, .06)
        background_color :[1,1,1,1]
        pos_hint :{'center_x':.5, 'center_y':.100}
        text :"Already Have Account,\n           Log In"
        on_release :
            app.root.current='login'
            root.manager.transition.direction = "up"
<homepage>:
    Image:
        source:r"Design\HomePageDesign.jpg"
        allow_stretch: True
        keep_ratio: False
    Spinner:
        id:spinner_id
        size_hint :(.1, .1)
        pos_hint : {'center_x':.490, 'center_y':.410}
        text:"Select class"
        values:["class1","class2","class3","class4","class5","class6","class7","class8","class9","class10"]
        on_text:
            root.fun(spinner_id.text)


